server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: ms-auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?allowPublicKeyRetieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    
## CONF PARA TOKEN    
security:
  jwt:
    token:
      secret-key: chave_microservices
      expire-length: 360000
    
logging:
  file:
    name: ../log/ms_auth_log/appfile.log
