server:
  port: 8080
    
spring:
  application:
    name: ms-api-gateway
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
      
zuul:
  prefix: /api
  ignored-services: "*"
  
  routes:
    ms-crud:
      path: /crud/**
      service-id: crud
      strip-prefix: false
      custom-sensitive-headers: true
      
    ms-pagamento:
      path: /pagamento/**
      service-id: pagamento
      strip-prefix: false
      custom-sensitive-headers: true
      
    ms-auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true           
                  